name: petbi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  intl: ^0.17.0
  intl_utils: ^2.7.0
  get_it: ^7.2.0
  dio: ^4.0.6
  auto_route: ^5.0.4
  url_launcher: ^6.1.9
  lottie: ^2.2.0
  flutter_hicons: ^0.0.1
  icons_plus: ^4.0.0
  collection: ^1.17.1
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3

  mocktail: ^0.3.0
  bloc_test: ^9.1.1
  http_mock_adapter: ^0.3.3
  

dependency_overrides: 
  collection: ^1.17.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/

flutter_gen:
  output: lib/generated/
  line_length: 120

  fonts:
    enabled: false

flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: en
  arb_dir: lib/src/core/i18n/l10n
  output_dir: lib/src/core/i18n
